name: Deploy Blinkit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
          chmod 400 ~/.ssh/ec2.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/ec2.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            set -e

            echo "Go to app directory"
            cd /home/ubuntu/BlinkIt-Clone-Full-Stack-Ecommerce

            echo "Pull latest code"
            git pull origin main

            echo "Frontend build"
            cd client
            npm install
            npm run build

            echo "Deploy frontend"
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            echo "Backend restart"
            cd ../server
            npm install
            pm2 restart blinkit-backend || pm2 start index.js --name blinkit-backend
            pm2 save

            echo "Reload nginx"
            sudo systemctl reload nginx
          EOF
